<center> <font color = #82318E size = 5 face = "微软雅黑" > NetCDF4 Test For Terminal Python </font> </center>

In [1]:
import os
import numpy as np
import pandas as pd
import netCDF4 as nc

import keras 
import tensorflow as tf

import seaborn as sns
import matplotlib.pyplot as plt

Using TensorFlow backend.


<center> <font color = #82318E size = 4 face = "微软雅黑" > 1. atm </font> </center>

<center> <font color = #82318E size = 3 face = "微软雅黑" > 1.1 Variables' Table </font> </center>

In [2]:
dir = './Samples/atm/'
nc_temp_list = list()

for file in os.listdir(dir):
    if file.split('.')[-1] == 'nc':
        print(file)
        nc_temp_list.append('{}{}'.format(dir, file))
print()

for i in np.arange(len(nc_temp_list)):
    print(nc_temp_list[i])

F1850_2011May7.gamil.h0.0446-03.nc
F1850_2011May7.gamil.h0.0446-04.nc
F1850_2011May7.gamil.h0.0446-05.nc
F1850_2011May7.gamil.h0.0446-06.nc
F1850_2011May7.gamil.h0.0446-07.nc
F1850_2011May7.gamil.h0.0446-08.nc
F1850_2011May7.gamil.h0.0446-09.nc
F1850_2011May7.gamil.h0.0446-10.nc
F1850_2011May7.gamil.h0.0446-11.nc
F1850_2011May7.gamil.h0.0446-12.nc
F1850_2011May7.gamil.h0.1604-01.nc
F1850_2011May7.gamil.h0.1604-02.nc
F1850_2011May7.gamil.h0.1604-03.nc
F1850_2011May7.gamil.h0.1604-04.nc
F1850_2011May7.gamil.h0.1604-05.nc
F1850_2011May7.gamil.h0.1604-06.nc
F1850_2011May7.gamil.h0.1604-07.nc
F1850_2011May7.gamil.h0.1604-08.nc
F1850_2011May7.gamil.h0.1604-09.nc
F1850_2011May7.gamil.h0.1604-10.nc
F1850_2011May7.gamil.h0.1604-11.nc
F1850_2011May7.gamil.h0.1604-12.nc

./Samples/atm/F1850_2011May7.gamil.h0.0446-03.nc
./Samples/atm/F1850_2011May7.gamil.h0.0446-04.nc
./Samples/atm/F1850_2011May7.gamil.h0.0446-05.nc
./Samples/atm/F1850_2011May7.gamil.h0.0446-06.nc
./Samples/atm/F1850_2011May7.gami

In [3]:
temp_pointer = nc.Dataset(nc_temp_list[0])

temp_dict = {}

for j in np.arange(len(list(temp_pointer.variables.keys()))):
    temp = temp_pointer.variables[list(temp_pointer.variables.keys())[j]]

    '''
    print('-'*25 + ' Variable {0:03d} '.format(j) + '-'*25)
    print(temp)
    print('-'*64, end = '\n'*2)
    '''
    
    if temp.name != 'date_written' and temp.name != 'time_written':
        temp_dict.setdefault('{0:03d}'.format(j), [temp.name, temp.long_name, temp.shape])
    else:
        temp_dict.setdefault('{0:03d}'.format(j), [temp.name, temp.name, temp.shape])
    
temp_df = pd.DataFrame(temp_dict, index = ['Name', 'Long_name', 'Shape']).transpose()
print(temp_df)

temp_df.to_excel('{}atm_Variables.xlsx'.format(dir), sheet_name = 'Sheet1')

             Name                                          Long_name  \
000            P0                                 reference pressure   
001           lat                                           latitude   
002           lon                                          longitude   
003           lev              sigma level at midpoints (1000*(A+B))   
004          ilev                          sigma level at interfaces   
005     isccp_prs                                Mean ISCCP pressure   
006     isccp_tau                           Mean ISCCP optical depth   
007  isccp_prstau  Mean pressure (mb).mean optical depth (unitles...   
008          time                                               time   
009     time_bnds                            time interval endpoints   
010  date_written                                       date_written   
011  time_written                                       time_written   
012        ndbase                                           base

<center> <font color = #82318E size = 3 face = "微软雅黑" > 1.2 TimeSeries Data </font> </center>

In [4]:
dir = './Samples/atm/'
temp_list = list()

for file in os.listdir(dir):
    if file.split('.')[-1] == 'nc':
        '''
        print(file)
        '''
        temp_list.append('{}{}'.format(dir, file))

temp_list.sort(reverse = False)

for i in np.arange(len(temp_list)):    
    print(temp_list[i])
    
print(len(temp_list))

./Samples/atm/F1850_2011May7.gamil.h0.0446-03.nc
./Samples/atm/F1850_2011May7.gamil.h0.0446-04.nc
./Samples/atm/F1850_2011May7.gamil.h0.0446-05.nc
./Samples/atm/F1850_2011May7.gamil.h0.0446-06.nc
./Samples/atm/F1850_2011May7.gamil.h0.0446-07.nc
./Samples/atm/F1850_2011May7.gamil.h0.0446-08.nc
./Samples/atm/F1850_2011May7.gamil.h0.0446-09.nc
./Samples/atm/F1850_2011May7.gamil.h0.0446-10.nc
./Samples/atm/F1850_2011May7.gamil.h0.0446-11.nc
./Samples/atm/F1850_2011May7.gamil.h0.0446-12.nc
./Samples/atm/F1850_2011May7.gamil.h0.1604-01.nc
./Samples/atm/F1850_2011May7.gamil.h0.1604-02.nc
./Samples/atm/F1850_2011May7.gamil.h0.1604-03.nc
./Samples/atm/F1850_2011May7.gamil.h0.1604-04.nc
./Samples/atm/F1850_2011May7.gamil.h0.1604-05.nc
./Samples/atm/F1850_2011May7.gamil.h0.1604-06.nc
./Samples/atm/F1850_2011May7.gamil.h0.1604-07.nc
./Samples/atm/F1850_2011May7.gamil.h0.1604-08.nc
./Samples/atm/F1850_2011May7.gamil.h0.1604-09.nc
./Samples/atm/F1850_2011May7.gamil.h0.1604-10.nc
./Samples/atm/F1850_

In [5]:
for i in temp_list:
    
    print(i)
    temp_pointer = nc.Dataset(i)
    time = temp_pointer.variables['time']
    
    '''
    print('='*64 + '\n' + '{}'.format(i))
    print(time.units)
    '''
    
    print(nc.num2date(time[:], time.units, calendar = '365_day'), end = '\n'*2)

./Samples/atm/F1850_2011May7.gamil.h0.0446-03.nc
[cftime.DatetimeNoLeap(446, 4, 1, 0, 0, 0, 0, 4, 91)]

./Samples/atm/F1850_2011May7.gamil.h0.0446-04.nc
[cftime.DatetimeNoLeap(446, 5, 1, 0, 0, 0, 0, 6, 121)]

./Samples/atm/F1850_2011May7.gamil.h0.0446-05.nc
[cftime.DatetimeNoLeap(446, 6, 1, 0, 0, 0, 0, 2, 152)]

./Samples/atm/F1850_2011May7.gamil.h0.0446-06.nc
[cftime.DatetimeNoLeap(446, 7, 1, 0, 0, 0, 0, 4, 182)]

./Samples/atm/F1850_2011May7.gamil.h0.0446-07.nc
[cftime.DatetimeNoLeap(446, 8, 1, 0, 0, 0, 0, 0, 213)]

./Samples/atm/F1850_2011May7.gamil.h0.0446-08.nc
[cftime.DatetimeNoLeap(446, 9, 1, 0, 0, 0, 0, 3, 244)]

./Samples/atm/F1850_2011May7.gamil.h0.0446-09.nc
[cftime.DatetimeNoLeap(446, 10, 1, 0, 0, 0, 0, 5, 274)]

./Samples/atm/F1850_2011May7.gamil.h0.0446-10.nc
[cftime.DatetimeNoLeap(446, 11, 1, 0, 0, 0, 0, 1, 305)]

./Samples/atm/F1850_2011May7.gamil.h0.0446-11.nc
[cftime.DatetimeNoLeap(446, 12, 1, 0, 0, 0, 0, 3, 335)]

./Samples/atm/F1850_2011May7.gamil.h0.0446-12.nc
[cft

In [6]:
'''
Eddy temperature variance
'''
string = 'TT'

I = len(temp_list)
J = nc.Dataset(temp_list[0]).variables[string].shape[-3]
K = nc.Dataset(temp_list[0]).variables[string].shape[-2]
L = nc.Dataset(temp_list[0]).variables[string].shape[-1]

temp_matrix = np.ones((I, J, K, L))
print(temp_matrix.shape)

for i in np.arange(len(temp_list)):
    
    temp_pointer = nc.Dataset(temp_list[i])
    temp_single_matrix = temp_pointer.variables[string]
    print(temp_single_matrix.shape)
    temp_matrix[i, ::, ::, ::] = temp_single_matrix[0, ::, ::, ::]

np.save('./Tensor/atm/{}.npy'.format(string), temp_matrix)

(22, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)


In [7]:
load_matrix = np.load('./Tensor/atm/{}.npy'.format(string))
'''
print(load_matrix)
'''
print(load_matrix.shape)

(22, 26, 60, 128)


<center> <font color = #82318E size = 3 face = "微软雅黑" > 1.3 Define Function </font> </center>

In [35]:
def NC2TimeSeriesNPY(*, string, temp_shape):

    I = len(temp_list)
    if temp_shape == 3:
        J = nc.Dataset(temp_list[0]).variables[string].shape[-3]
        K = nc.Dataset(temp_list[0]).variables[string].shape[-2]
        L = nc.Dataset(temp_list[0]).variables[string].shape[-1]
        temp_matrix = np.ones((I, J, K, L))
        print(temp_matrix.shape)

        for i in np.arange(I):
            with nc.Dataset(temp_list[i]) as temp_pointer:
                temp_single_matrix = temp_pointer.variables[string]
                print(temp_single_matrix.shape)
                temp_matrix[i, ::, ::, ::] = temp_single_matrix[::]


    elif temp_shape == 2:
        J = nc.Dataset(temp_list[0]).variables[string].shape[-2]
        K = nc.Dataset(temp_list[0]).variables[string].shape[-1]
        temp_matrix = np.ones((I, J, K))
        print(temp_matrix.shape)

        for i in np.arange(I):
            with nc.Dataset(temp_list[i]) as temp_pointer:
                temp_single_matrix = temp_pointer.variables[string]
                print(temp_single_matrix.shape)
                temp_matrix[i, ::, ::] = temp_single_matrix[::]

    elif temp_shape == 1:
        J = nc.Dataset(temp_list[0]).variables[string].shape[-1]
        temp_matrix = np.ones((I, J))
        print(temp_matrix.shape)

        for i in np.arange(I):
            with nc.Dataset(temp_list[i]) as temp_pointer:
                temp_single_matrix = temp_pointer.variables[string]
                print(temp_single_matrix.shape)
                temp_matrix[i, ::] = temp_single_matrix[::]

    else:
        temp_matrix = np.ones((I, ))
        print(temp_matrix.shape)

        for i in np.arange(I):
            with nc.Dataset(temp_list[i]) as temp_pointer:
                temp_single_matrix = temp_pointer.variables[string]
                print(temp_single_matrix.shape)
                temp_matrix[i] = temp_single_matrix[::]

    np.save('./Tensor/atm/{}.npy'.format(string), temp_matrix)        

In [45]:
help(pd.read_excel)

Help on function read_excel in module pandas.io.excel:

read_excel(io, sheet_name=0, header=0, skiprows=None, skip_footer=0, index_col=None, names=None, usecols=None, parse_dates=False, date_parser=None, na_values=None, thousands=None, convert_float=True, converters=None, dtype=None, true_values=None, false_values=None, engine=None, squeeze=False, **kwds)
    Read an Excel table into a pandas DataFrame
    
    Parameters
    ----------
    io : string, path object (pathlib.Path or py._path.local.LocalPath),
        file-like object, pandas ExcelFile, or xlrd workbook.
        The string could be a URL. Valid URL schemes include http, ftp, s3,
        and file. For file URLs, a host is expected. For instance, a local
        file could be file://localhost/path/to/workbook.xlsx
    sheet_name : string, int, mixed list of strings/ints, or None, default 0
    
        Strings are used for sheet names, Integers are used in zero-indexed
        sheet positions.
    
        Lists of strings

In [64]:
temp_variables_dictionary = pd.read_excel('./Samples/atm/atm_shape.xlsx', header = 0)

In [66]:
processing_variables_dictionary = {}
for i in np.arange(temp_variables_dictionary.values.shape[0]):
    processing_variables_dictionary.setdefault(temp_variables_dictionary.iloc[i, 0], temp_variables_dictionary.iloc[i, 1])
'''
print(processing_variables_dictionary)
'''  
for key, value in processing_variables_dictionary.items():
    NC2TimeSeriesNPY(string = key, temp_shape = value)
    load_matrix = np.load('./Tensor/atm/{}.npy'.format(key))
    print(load_matrix)
    print(load_matrix.shape)

(22,)
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[100000. 100000. 100000. 100000. 100000. 100000. 100000. 100000. 100000.
 100000. 100000. 100000. 100000. 100000. 100000. 100000. 100000. 100000.
 100000. 100000. 100000. 100000.]
(22,)
(22, 60)
(60,)
(60,)
(60,)
(60,)
(60,)
(60,)
(60,)
(60,)
(60,)
(60,)
(60,)
(60,)
(60,)
(60,)
(60,)
(60,)
(60,)
(60,)
(60,)
(60,)
(60,)
(60,)
[[-90.         -83.86854332 -79.15281595 ...  79.15281595  83.86854332
   90.        ]
 [-90.         -83.86854332 -79.15281595 ...  79.15281595  83.86854332
   90.        ]
 [-90.         -83.86854332 -79.15281595 ...  79.15281595  83.86854332
   90.        ]
 ...
 [-90.         -83.86854332 -79.15281595 ...  79.15281595  83.86854332
   90.        ]
 [-90.         -83.86854332 -79.15281595 ...  79.15281595  83.86854332
   90.        ]
 [-90.         -83.86854332 -79.15281595 ...  79.15281595  83.86854332
   90.        ]]
(22, 60)
(22, 128)
(128,)
(128,)
(128,)
(128,)
(128,)
(128,)
(128,)
(128,

(27,)
(27,)
(27,)
(27,)
[[0.         0.00267215 0.00760584 0.01568776 0.02734652 0.04197394
  0.05877423 0.07549935 0.08939827 0.10574965 0.12498618 0.14761697
  0.17424094 0.20556259 0.242411   0.28576119 0.33676041 0.39675836
  0.46734282 0.55038186 0.64807298 0.74355909 0.83048229 0.90299899
  0.95586942 0.98507989 1.        ]
 [0.         0.00267215 0.00760584 0.01568776 0.02734652 0.04197394
  0.05877423 0.07549935 0.08939827 0.10574965 0.12498618 0.14761697
  0.17424094 0.20556259 0.242411   0.28576119 0.33676041 0.39675836
  0.46734282 0.55038186 0.64807298 0.74355909 0.83048229 0.90299899
  0.95586942 0.98507989 1.        ]
 [0.         0.00267215 0.00760584 0.01568776 0.02734652 0.04197394
  0.05877423 0.07549935 0.08939827 0.10574965 0.12498618 0.14761697
  0.17424094 0.20556259 0.242411   0.28576119 0.33676041 0.39675836
  0.46734282 0.55038186 0.64807298 0.74355909 0.83048229 0.90299899
  0.95586942 0.98507989 1.        ]
 [0.         0.00267215 0.00760584 0.01568776 0.0273

(49,)
(49,)
(49,)
(49,)
(49,)
(49,)
(49,)
(49,)
(49,)
(49,)
(49,)
(49,)
(49,)
(49,)
(49,)
(49,)
(49,)
(49,)
[[ 90.00015  90.0008   90.00245 ... 900.0162  900.0415  900.2195 ]
 [ 90.00015  90.0008   90.00245 ... 900.0162  900.0415  900.2195 ]
 [ 90.00015  90.0008   90.00245 ... 900.0162  900.0415  900.2195 ]
 ...
 [ 90.00015  90.0008   90.00245 ... 900.0162  900.0415  900.2195 ]
 [ 90.00015  90.0008   90.00245 ... 900.0162  900.0415  900.2195 ]
 [ 90.00015  90.0008   90.00245 ... 900.0162  900.0415  900.2195 ]]
(22, 49)
(22,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
[158865. 158895. 158926. 158956. 158987. 159018. 159048. 159079. 159109.
 159140. 581476. 581504. 581535. 581565. 581596. 581626. 581657. 581688.
 581718. 581749. 581779. 581810.]
(22,)
(22, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)
[[158834. 1

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0.

(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[17.92145729 17.92145729 17.92145729 ... 17.92145729 17.92145729
   17.92145729]
  [24.5871582  25.23571777 25.01401138 ... 24.18259621 23.81965446
   24.7267189 ]
  [23.3932724  25.37915802 26.19578171 ... 21.11088562 22.23970795
   21.96652222]
  ...
  [21.27743149 21.54055214 21.24972534 ... 21.50991249 21.36665916
   21.55091095]
  [23.13438606 22.87634659 23.52727699 ... 22.54016113 23.25949478
   23.46923447]
  [30.34583282 30.34583664 30.34583282 ... 30.34583282 30.34583282
   30.34583473]]

 [[15.93070507 15.93070507 15.93070507 ... 15.93070507 15.93070507
   15.93070507]
  [20.7474556  19.96776962 20.93260956 ... 21.41281128 20.93938255
   20.6548214 ]
  [20.16866684 20.36750412 20.52507591 ... 20.65471649 21.17117691
   20.20326042

(22, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   ...
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00

(22, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   ...
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   ...
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]]

  [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   ...
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]]

  [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   ...
   [0.

(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[2.65926875e+05 2.65926875e+05 2.65926875e+05 ... 2.65926875e+05
   2.65926875e+05 2.65926875e+05]
  [2.94459878e+09 1.80502592e+09 8.85526016e+08 ... 5.69627085e+09
   4.89286349e+09 4.05720755e+09]
  [2.19547008e+09 9.97026688e+08 3.83758976e+08 ... 8.51562701e+09
   6.26608435e+09 4.44351078e+09]
  ...
  [7.23060429e+09 7.36570010e+09 6.74435021e+09 ... 7.33970074e+09
   7.44730061e+09 7.64598886e+09]
  [3.26829466e+09 3.72811878e+09 3.07844173e+09 ... 3.26993050e+09
   3.37127680e+09 3.28827597e+09]
  [4.05105350e+06 4.05105325e+06 4.05105300e+06 ... 4.05105275e+06
   4.05105275e+06 4.05105350e+06]]

 [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [7.24330720e+07 4.35980547e+04 2.82291920e+07 ...

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   ...
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]]

  [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   ...
   [0.

(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[0.5527845  0.5527845  0.5527845  ... 0.5527845  0.5527845  0.5527845 ]
  [0.         0.         0.         ... 0.45623693 0.39194915 0.00384348]
  [0.         0.         0.         ... 0.40655017 0.00474831 0.        ]
  ...
  [0.24413429 0.26179591 0.2433885  ... 0.16381852 0.20257014 0.21545359]
  [0.16303661 0.19658136 0.18375714 ... 0.1173191  0.13457805 0.14783591]
  [0.16969971 0.16969968 0.16969968 ... 0.16969971 0.16969971 0.16969971]]

 [[0.09231395 0.09231395 0.09231395 ... 0.09231395 0.09231395 0.09231395]
  [0.         0.         0.         ... 0.21834008 0.01764619 0.        ]
  [0.         0.         0.         ... 0.3733069  0.         0.        ]
  ...
  [0.24230722 0.240033   0.27236643 ... 0.12492389 0.1302132

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   ...
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]]

  [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 

(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
    -0.00000000e+00 -0.00000000e+00]
   [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
    -0.00000000e+00 -0.00000000e+00]
   [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
    -0.00000000e+00 -0.00000000e+00]
   ...
   [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -5.61888735e-38
    -2.31373613e-37 -0.00000000e+00]
   [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
    -6.50515975e-37 -0.00000000e+00]
   [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
    -0.00000000e+00 -0.00000000e+00]]

  [[-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
    -0.00000000e+00 -0.00000000e+00]
   [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
    -0.00000000e+00 -0.00000000e+00]
   [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
    -0.000000

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   ...
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]]

  [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   ...
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]]

  [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e

(22, 27, 60, 128)
(1, 27, 60, 128)
(1, 27, 60, 128)
(1, 27, 60, 128)
(1, 27, 60, 128)
(1, 27, 60, 128)
(1, 27, 60, 128)
(1, 27, 60, 128)
(1, 27, 60, 128)
(1, 27, 60, 128)
(1, 27, 60, 128)
(1, 27, 60, 128)
(1, 27, 60, 128)
(1, 27, 60, 128)
(1, 27, 60, 128)
(1, 27, 60, 128)
(1, 27, 60, 128)
(1, 27, 60, 128)
(1, 27, 60, 128)
(1, 27, 60, 128)
(1, 27, 60, 128)
(1, 27, 60, 128)
(1, 27, 60, 128)
[[[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   ...
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00

(22, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[0.02763375 0.02763375 0.02763375 ... 0.02763375 0.02763375 0.02763375]
  [0.02043818 0.02090367 0.02637417 ... 0.01865928 0.0241269  0.02246969]
  [0.01636449 0.01021648 0.01413389 ... 0.01764475 0.01488521 0.01125383]
  ...
  [0.02942551 0.03098968 0.02874509 ... 0.02927232 0.02656589 0.02907183]
  [0.03434624 0.02957156 0.03137842 ... 0.02900799 0.03244549 0.02883895]
  [0.         0.         0.         ... 0.         0.         0.        ]]

 [[0.05106039 0.05106039 0.05106039 ... 0.05106039 0.05106039 0.05106039]
  [0.03299796 0.03025603 0.02991751 ... 0.03323139 0.03668262 0.03033449]
  [0.02511226 0.03185521 0.02985267 ... 0.01910873 0.02495268 0.02181056]
  ...
  [0.02604489 0.0249

(1, 60, 128)
[[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  ...
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]]

 [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  ...
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+

(22, 60, 128)
(22, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[1.37093514e-06 1.37093514e-06 1.37093525e-06 ... 1.37093514e-06
   1.37093514e-06 1.37093514e-06]
  [4.01888065e-06 3.94906419e-06 3.52605548e-06 ... 5.60031867e-06
   4.89770946e-06 4.21159893e-06]
  [2.81350776e-06 2.43917520e-06 2.29369289e-06 ... 5.62032892e-06
   4.34609910e-06 3.60635863e-06]
  ...
  [2.66969073e-05 2.51492147e-05 2.30570768e-05 ... 2.50277390e-05
   2.79636697e-05 2.95710088e-05]
  [1.56731749e-05 1.67022699e-05 1.43538864e-05 ... 1.51636859e-05
   1.61646549e-05 1.59123283e-05]
  [4.62887158e-07 4.62887130e-07 4.62887186e-07 ... 4.62887186e-07
   4.62887158e-07 4.62887243e-07]]

 [[5.45565342e-07 5.45565342e-07 5.45565342e-07 ... 5.45565342e-07
   5.

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   ...
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]]

  [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+0

     4.94321557e-06  4.94321557e-06]]]]
(22, 26, 60, 128)
(22, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  ...

  [[0. 0. 0. ... 0. 0. 0.]
   

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[25.         25.         25.         ... 25.         25.
    25.        ]
   [25.         25.         25.         ... 25.         25.
    25.        ]
   [25.         25.         25.         ... 25.         25.
    25.        ]
   ...
   [25.         25.         25.         ... 25.         25.
    25.        ]
   [25.         25.         25.         ... 25.         25.
    25.        ]
   [25.         25.         25.         ... 25.         25.
    25.        ]]

  [[25.         25.         25.         ... 25.         25.
    25.        ]
   [25.         25.         25.         ... 25.         25.
    25.        ]
   [25.         25.         25.         ... 25.         25.
    25.        ]
   ...
   [25.         25.         25.         ... 25.         25.
    25.        ]
   [25.         25.         25.         ... 25.         25.
    25.        ]
   [25.         25.         25.    

(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[10.         10.         10.         ... 10.         10.
    10.        ]
   [10.         10.         10.         ... 10.         10.
    10.        ]
   [10.         10.         10.         ... 10.         10.
    10.        ]
   ...
   [10.         10.         10.         ... 10.         10.
    10.        ]
   [10.         10.         10.         ... 10.         10.
    10.        ]
   [10.         10.         10.         ... 10.         10.
    10.        ]]

  [[10.         10.         10.         ... 10.         10.
    10.        ]
   [10.         10.         10.         ... 10.         10.
    10.        ]
   [10.         10.         10.         ... 10.         10.
    10.        ]
   ...
   [10.         10.         10.         ... 10.         10.
    10.        ]
   [10.         10.         10.         ... 10.         10.
    10.        ]
   [10.         10.         10.         ... 10.         10.
    10.        ]]

  [[10.         10.     

(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. .

(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[142.83717346 142.83842468 142.83729553 ... 142.83721924 142.8371582
   142.83911133]
  [140.67437744 140.06422424 138.21995544 ... 145.58534241 144.06732178
   142.23957825]
  [141.76808167 139.06135559 136.93341064 ... 150.2585144  147.09162903
   143.668396  ]
  ...
  [156.05776978 158.30012512 159.41090393 ... 151.28044128 153.04476929
   154.17703247]
  [145.68383789 146.45916748 146.59101868 ... 145.24772644 145.08506775
   145.29109192]
  [136.27154541 136.28797913 136.27328491 ... 136.14070129 136.16096497
   136.2273407 ]]

 [[127.69207764 127.69340515 127.69218445 ... 127.69215393 127.69205475
   127.69405365]
  [127.17186737 125.14144135 124.08730316 ... 131.72441101 130.24436951
   129.03759766]
  [130.7

(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[2.93908386e+01 2.93907795e+01 2.93907528e+01 ... 2.93909683e+01
   2.93909264e+01 2.93908577e+01]
  [4.73751488e+01 4.78898277e+01 4.78164330e+01 ... 4.49571648e+01
   4.60155716e+01 4.66562614e+01]
  [7.20309067e+01 7.27222519e+01 7.24626312e+01 ... 6.83109894e+01
   6.98181686e+01 7.07803421e+01]
  ...
  [3.18794460e+01 3.17494812e+01 3.13722019e+01 ... 3.20220337e+01
   3.15700188e+01 3.15285606e+01]
  [1.68593502e+01 1.67603760e+01 1.67964802e+01 ... 1.67891407e+01
   1.68422108e+01 1.68629093e+01]
  [6.70326614e+00 6.70326328e+00 6.70284271e+00 ... 6.70316124e+00
   6.70308352e+00 6.70292902e+00]]

 [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [2.23721296e-01 2.25271478e-01 2.21576124e-01 ...

(1, 60, 128)
[[[7.44260645e+00 7.44274139e+00 7.44259930e+00 ... 7.44262123e+00
   7.44261265e+00 7.44279766e+00]
  [1.08524485e+01 1.08968964e+01 1.09398689e+01 ... 1.06770134e+01
   1.07387028e+01 1.07908487e+01]
  [1.64981041e+01 1.65600414e+01 1.66295662e+01 ... 1.61366272e+01
   1.62890148e+01 1.64073887e+01]
  ...
  [9.45787239e+00 9.68282700e+00 9.90612698e+00 ... 9.14796448e+00
   9.23842621e+00 9.31022930e+00]
  [4.38563108e+00 4.35736847e+00 4.38202906e+00 ... 4.40292883e+00
   4.39116859e+00 4.38479185e+00]
  [2.40033364e+00 2.40058875e+00 2.40700269e+00 ... 2.40328622e+00
   2.40409327e+00 2.40624690e+00]]

 [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [5.12803271e-02 5.15685193e-02 5.13666235e-02 ... 4.98006009e-02
   5.03559485e-02 5.06629236e-02]
  [1.03151464e+00 1.04048347e+00 1.04979467e+00 ... 9.94840860e-01
   1.00603855e+00 1.01849735e+00]
  ...
  [3.99105301e+01 4.08050804e+01 4.35733070e+01 ... 3.97092819e+

(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[ 21.63019371  21.63041878  21.63037682 ...  21.62991714  21.63000488
    21.63028336]
  [ 25.56967926  25.4781971   25.3846035  ...  25.95146751  25.81874084
    25.70377159]
  [ 33.28865814  33.17501068  33.04437256 ...  34.07607651  33.72395325
    33.46968842]
  ...
  [ 26.08488083  26.39075089  26.60173225 ...  25.56171608  25.74921608
    25.90874481]
  [ 13.96472931  13.93074512  13.94432354 ...  14.03214073  14.01490784
    13.99318123]
  [  8.28226757   8.28251553   8.28877068 ...   8.28520012   8.28596973
     8.288064  ]]

 [[  0.           0.           0.         ...   0.           0.
     0.        ]
  [  0.23943196   0.24134445   0.23967132 ...   0.23717889   0.23539208
     0.23710509]
  [  3.03237367   3.01247597   2.99518037 ...   3.12671089   3.10030627
     3.06542325]
  ...
  [ 90.2432

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   ...
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.34854653e-37
    5.55302251e-37 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    1.56125402e-36 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]]

  [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   ...
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]]

  [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   ...
   [0.

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   ...
   [5.86778598e-37 6.61247455e-37 1.59638825e-37 ... 3.63570338e-33
    1.49181165e-32 1.00335167e-36]
   [1.78584131e-36 1.63767191e-36 2.03256347e-37 ... 5.20893804e-37
    4.28881289e-32 6.08615447e-37]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]]

  [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   ...
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]]

  [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   ...
   [0.

(22, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   ...
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00

(22, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[1.         1.         1.         ... 1.         1.         1.        ]
  [1.         1.         1.         ... 1.         1.         1.        ]
  [1.         1.         1.         ... 1.         1.         1.        ]
  ...
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.66527116 0.66527253 0.66527367 ... 0.66527385 0.66527367 0.66527253]]

 [[1.         1.         1.         ... 1.         1.         1.        ]
  [1.         1.         1.         ... 1.         1.         1.        ]
  [1.         1.         1.         ... 1.         1.         1.        ]
  ...
  [0.         0.    

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[4.86365898e-05 4.86365898e-05 4.86365898e-05 ... 4.86365898e-05
    4.86365898e-05 4.86365898e-05]
   [4.17002302e-05 4.14723836e-05 4.11258989e-05 ... 4.36729933e-05
    4.27996602e-05 4.27021405e-05]
   [3.62108512e-05 3.54163931e-05 3.50312730e-05 ... 3.86414067e-05
    3.75931268e-05 3.68252513e-05]
   ...
   [5.04231393e-05 5.04721538e-05 5.04457457e-05 ... 4.85777637e-05
    4.95876993e-05 4.99241469e-05]
   [5.56246814e-05 5.57471867e-05 5.54145627e-05 ... 5.49330543e-05
    5.48554890e-05 5.53786995e-05]
   [6.32867668e-05 6.32867668e-05 6.32867668e-05 ... 6.32867668e-05
    6.32867668e-05 6.32867668e-05]]

  [[8.81172309e-05 8.81172309e-05 8.81172309e-05 ... 8.81172309e-05
    8.81172309e-05 8.81172309e-05

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   ...
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]]

  [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000

(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   ...
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]]

  [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   ...
   [0.00000000e+00 0.00

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[6.35119113e-06 6.35119113e-06 6.35119113e-06 ... 6.35119113e-06
    6.35119113e-06 6.35119113e-06]
   [6.35861761e-06 6.36190953e-06 6.36492950e-06 ... 6.34718754e-06
    6.35125070e-06 6.35506331e-06]
   [6.44752072e-06 6.45258706e-06 6.45676255e-06 ... 6.42684199e-06
    6.43461681e-06 6.44151987e-06]
   ...
   [7.01847603e-06 7.01825866e-06 7.01816498e-06 ... 7.02041189e-06
    7.01950739e-06 7.01887348e-06]
   [6.97415226e-06 6.97399673e-06 6.97387804e-06 ... 6.97492305e-06
    6.97462247e-06 6.97436462e-06]
   [6.97355608e-06 6.97355608e-06 6.97355608e-06 ... 6.97355608e-06
    6.97355608e-06 6.97355608e-06]]


(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[-2.18131208e-06 -2.18131208e-06 -2.18131208e-06 ... -2.18131208e-06
    -2.18131208e-06 -2.18131208e-06]
   [-1.84639684e-05  3.31721494e-05 -6.69623405e-05 ...  8.13163642e-05
    -2.09157413e-04 -3.99179582e-04]
   [ 1.34954389e-04  1.56990485e-04  2.80745793e-04 ...  1.78983784e-04
     1.02872844e-04 -3.09339812e-05]
   ...
   [-2.39890200e-04  4.80737042e-04  7.06389197e-04 ...  1.71771244e-04
    -3.65677697e-04 -7.05368409e-04]
   [ 9.85093880e-04 -1.59958377e-03 -6.05957815e-04 ...  9.64964740e-04
    -3.77697463e-04  9.05356428e-04]
   [ 1.40616045e-04  1.40616045e-04  1.40616045e-04 ...  1.40616045e-04
     1.40616045e-04  1.40616045e-04]]

  [[-1.65115380e-05 -1.65115380e-05 -1.65115380e-05 ... -1.65115380e-05
    -1.65115380e-05 -1.65115380e-05]
   [-1.

(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[-3.66716791e-04 -3.66716791e-04 -3.66716791e-04 ... -3.66716791e-04
    -3.66716791e-04 -3.66716791e-04]
   [ 5.08641526e-02  5.97416945e-02  4.12825644e-02 ...  6.80603012e-02
     3.56298173e-03 -3.36746983e-02]
   [ 3.78923751e-02  4.39610556e-02  6.99405521e-02 ...  4.98933122e-02
     3.01522594e-02  3.85601260e-03]
   ...
   [-2.89084781e-02  1.26319483e-01  1.70739338e-01 ...  6.17650002e-02
    -4.59963642e-02 -1.19328834e-01]
   [ 3.17432523e-01 -1.99855760e-01 -1.79310217e-02 ...  3.07443112e-01
     3.15391049e-02  2.92351305e-01]
   [ 3.00961919e-02  3.00961919e-02  3.00961919e-02 ...  3.00961919e-02
     3.00961919e-02  3.00961919e-02]]

  [[-2.78900610e-03 -2.78900610e-03 -2.78900610e-03 ... -2.78900610e-03
    -2.78900610e-03 -2.78900610e-03]
   [-9.35865100e-03 -2.35674381e-02 -5.63921705e-02 ... -1.01037353e-01
    -6.71427995e-02 -9.49398354e-02]
   [ 1.04333997e-01  8.23495686e-02  4.65413220e-02 ...  1.26941204e-01
     1.199916

(22, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 7.96749629e-03  1.15243606e-02  1.44283799e-02 ...  9.59167629e-03
     6.54283212e-03  1.10788513e-02]
   [ 5.30953635e-04  3.55040189e-03  3.57595412e-03 ...  3.01690423e-03
    -7.62524141e-04 -1.30854140e-03]
   ...
   [ 1.54238706e-02  1.77650750e-02 -8.81948392e-04 ...  7.98368361e-03
     1.84346661e-02 -5.86926518e-03]
   [-2.50025317e-02  1.21771701e-01  9.14107934e-02 ...  1.29217729e-02
     6.37485385e-02  1.90458912e-02]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ... 

(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[2.51328203e+04 2.51328203e+04 2.51328203e+04 ... 2.51328203e+04
   2.51328203e+04 2.51328203e+04]
  [2.68968125e+04 2.76254590e+04 2.83017520e+04 ... 2.44126699e+04
   2.52872988e+04 2.61166543e+04]
  [2.90893477e+04 3.02613926e+04 3.12439121e+04 ... 2.44950625e+04
   2.61928008e+04 2.77299355e+04]
  ...
  [3.06882202e+02 1.33818558e+02 5.80653992e+01 ... 1.74366846e+03
   1.08100037e+03 6.11491333e+02]
  [1.92023758e+02 8.30009003e+01 3.46958899e+00 ... 7.26996704e+02
   5.12121460e+02 3.34191528e+02]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]]

 [[2.51328203e+04 2.51328203e+04 2.51328203e+04 ... 2.51328203e+04
   2.51328203e+04 2.51328203e+04]
  [2.68968125e+04 2.76254590e+04 2.83017520e+04 ... 2.44126699e+04
   2.52872988e+04 2.61166543e+04]
  [2.90893477e+04 3.02613926e+04 3.12439121e+04 ... 2.44950625e+04


(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[5.02193669e-11 5.02193669e-11 5.02193669e-11 ... 5.02193669e-11
   5.02193669e-11 5.02193669e-11]
  [4.29661029e-11 3.81387769e-11 3.82766006e-11 ... 3.91436501e-11
   3.86839068e-11 7.91034252e-11]
  [4.83752448e-11 3.42586966e-11 6.73939168e-11 ... 8.55528356e-11
   7.34098199e-11 4.71878508e-11]
  ...
  [4.69712658e-10 6.52165877e-10 5.37668798e-10 ... 6.15126172e-10
   5.00629371e-10 5.00247621e-10]
  [2.75875711e-10 1.73393036e-10 2.42235093e-10 ... 1.78493303e-10
   2.37057068e-10 2.79852003e-10]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]]

 [[2.74314294e-10 2.74314294e-10 2.74314294e-10 ... 2.74314294e-10
   2.74314294e-10 2.74314294e-10]
  [7.89169147e-11 6.80540208e-11 5.26277286e-11 ... 1.21734164e-10
   7.97177532e-11 7.08153466e-11]
  [2.55877125e-10 2.33151470e-10 1.502079

(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[8.38239966e-09 8.38239966e-09 8.38239966e-09 ... 8.38239966e-09
   8.38239966e-09 8.38239966e-09]
  [1.18406319e-07 1.31489102e-07 9.99038932e-08 ... 1.41442968e-07
   1.23439349e-07 1.29752621e-07]
  [6.68503546e-08 4.50857023e-08 4.52499229e-08 ... 1.16359800e-07
   9.33049336e-08 7.20476621e-08]
  ...
  [6.08436665e-07 6.46357933e-07 5.18712852e-07 ... 7.71739280e-07
   6.97530822e-07 7.03843000e-07]
  [6.58855299e-07 5.90091986e-07 6.28026953e-07 ... 6.78417621e-07
   4.92783727e-07 5.49218669e-07]
  [3.28484284e-09 3.28484284e-09 3.28484284e-09 ... 3.28484284e-09
   3.28484284e-09 3.28484284e-09]]

 [[5.03016473e-09 5.03016473e-09 5.03016473e-09 ... 5.03016473e-09
   5.03016473e-09 5.03016473e-09]
  [6.58167352e-08 9.18861716e-08 7.76027207e-08 ... 1.20283815e-07
   1.28325169e-07 1.18581539e-07]
  [6.72907063e-08 5.40006084e-08 3.30893890e-08 ... 1.

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[2.52995369e-06 2.52995369e-06 2.52995369e-06 ... 2.52995369e-06
    2.52995369e-06 2.52995369e-06]
   [2.21934852e-06 2.23018355e-06 2.23300276e-06 ... 2.24402856e-06
    2.22646941e-06 2.24766222e-06]
   [1.98852945e-06 1.97759459e-06 1.98365797e-06 ... 1.98783914e-06
    1.98093426e-06 1.98339762e-06]
   ...
   [1.83843258e-06 1.83637599e-06 1.83376596e-06 ... 1.80458153e-06
    1.82586814e-06 1.82702820e-06]
   [2.01697026e-06 2.01832268e-06 2.00394743e-06 ... 2.00630734e-06
    1.99772330e-06 2.01185503e-06]
   [2.28218823e-06 2.28218823e-06 2.28218823e-06 ... 2.28218823e-06
    2.28218823e-06 2.28218823e-06]]

  [[2.48251149e-06 2.48251149e-06 2.48251149e-06 ... 2.48251149e-06
    2.48251149e-06 2.48251149e-06]
   [2.21268783e-06 2.21146024e-06 2.21808659e-06 ... 2.22184894e-0

(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[6.82495269e-08 6.83346286e-08 6.82667221e-08 ... 6.82473456e-08
   6.82373056e-08 6.83849137e-08]
  [4.05747400e-08 3.59832306e-08 1.99994226e-08 ... 1.61002745e-07
   9.88998181e-08 6.94142770e-08]
  [1.70698272e-07 1.10098071e-07 8.39486916e-08 ... 2.34658614e-06
   1.40388340e-06 5.59170076e-07]
  ...
  [1.33824660e-05 1.97159152e-05 2.08175006e-05 ... 8.05884883e-06
   8.91167929e-06 1.04536775e-05]
  [4.17906222e-06 4.08528649e-06 5.19723653e-06 ... 4.36017081e-06
   3.71756073e-06 4.03749846e-06]
  [9.54105781e-06 8.94462846e-06 9.23180505e-06 ... 9.53276049e-06
   8.62248453e-06 8.32016030e-06]]

 [[5.51741053e-09 5.52202728e-09 5.51918289e-09 ... 5.51100277e-09
   5.50613244e-09 5.50552315e-09]
  [1.99766070e-08 1.29017996e-08 5.39575673e-09 ... 4.35901910e-08
   3.13126449e-08 3.51663552e-08]
  [9.45593257e-08 2.52797694e-08 4.79264539e-09 ... 3.03856950e-07
   2.98751530e-07 6.326023

(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[1.78784958e-05 1.78784885e-05 1.78784867e-05 ... 1.78785122e-05
    1.78785067e-05 1.78784976e-05]
   [1.94461300e-05 1.94548375e-05 1.94737277e-05 ... 1.93651067e-05
    1.93642754e-05 1.94098520e-05]
   [2.19180893e-05 2.19630292e-05 2.19898920e-05 ... 2.16771186e-05
    2.17254510e-05 2.18285477e-05]
   ...
   [1.43456564e-05 1.43338993e-05 1.43294246e-05 ... 1.44119795e-05
    1.44118194e-05 1.43795187e-05]
   [9.75002877e-06 9.77261698e-06 9.76230604e-06 ... 9.78035041e-06
    9.80096411e-06 9.79224569e-06]
   [7.28976875e-06 7.28977102e-06 7.28968052e-06 ... 7.28976056e-06
    7.28973646e-06 7.28970463e-06]]

  [[1.33347448e-05 1.33347385e-05 1.33347366e-05 ... 1.33347585e-05
    1.33347539e-05 1.33347467e-05]
   [1.42128911e-05 1.42471263e-05 1.42944318e-05 ... 1.40460470e-05
    1.40877710e-05 1.41496985e-05]
   [1.56112019e-05 1.57014638e-05 1.57645354e-05 ... 1.52200582e-05
    1.53365108e-05 1.54829795e-05]
   ...
   [1.07824335e-05 1.07

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[3.52363139e-02 3.52363139e-02 3.52363139e-02 ... 3.52363139e-02
    3.52363139e-02 3.52363139e-02]
   [5.91187850e-02 5.46294935e-02 5.37860468e-02 ... 5.40158860e-02
    5.55099286e-02 6.04119562e-02]
   [3.88661362e-02 3.91863622e-02 3.69633734e-02 ... 3.74168679e-02
    3.71028557e-02 3.69469896e-02]
   ...
   [4.77395266e-01 4.53528851e-01 3.86687785e-01 ... 4.75479484e-01
    4.12975878e-01 4.40548450e-01]
   [6.77722633e-01 6.13965333e-01 5.57520390e-01 ... 5.94743907e-01
    6.02766693e-01 6.33929074e-01]
   [2.35063657e-01 2.35063657e-01 2.35063657e-01 ... 2.35063657e-01
    2.35063657e-01 2.35063657e-01]]


(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0

(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0.

(22, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[-1.46806192e+00 -1.46813416e+00 -1.46811211e+00 ... -1.46798468e+00
   -1.46800864e+00 -1.46810019e+00]
  [-5.19280255e-01 -4.56039965e-01 -4.75162596e-01 ... -7.12371349e-01
   -6.07852221e-01 -5.76672852e-01]
  [-6.71556652e-01 -6.06758475e-01 -6.28029704e-01 ... -1.02102900e+00
   -8.55169296e-01 -7.71112025e-01]
  ...
  [-2.09899783e+00 -2.05200863e+00 -2.22780943e+00 ... -2.04299974e+00
   -2.11050415e+00 -2.14379954e+00]
  [-5.64002693e-01 -5.81503570e-01 -5.99367082e-01 ... -6.53157532e-01
   -6.07260168e-01 -6.13644123e-01]
  [-5.89859933e-02 -5.90009093e-02 -5.91281131e-02 ... -5.90527430e-02
   -5.90633340e-02 -5.91106042e-02]]

 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00

[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
    0.00000000e+00  0.00000000e+00]
  [ 8.34122971e-02  9.21397805e-02  8.13688859e-02 ...  8.94141719e-02
    9.04256403e-02  8.52865800e-02]
  [ 4.84923087e-02  4.13289852e-02  3.80378738e-02 ...  6.16287142e-02
    5.59972376e-02  5.11144400e-02]
  ...
  [ 5.25305197e-02  3.57616581e-02  2.32506413e-02 ...  1.08549319e-01
    8.31853896e-02  6.26620799e-02]
  [ 1.98707059e-02  1.68011189e-02  1.74046718e-02 ...  3.61563824e-02
    2.99213845e-02  2.46889871e-02]
  [ 1.54874905e-03  1.52443245e-03  1.52069400e-03 ...  2.02624989e-03
    1.90040655e-03  1.69867906e-03]]

 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
    0.00000000e+00  0.00000000e+00]
  [ 1.18508413e-01  1.15962759e-01  1.13255695e-01 ...  1.34346530e-01
    1.17294237e-01  1.25545576e-01]
  [ 6.04543723e-02  4.42186184e-02  3.22331786e-02 ...  1.17150970e-01
    1.02547370e-01  7.16838688e-02]
  ...
  [ 2.08267905e-02  2.4

(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[0.69705623 0.69705623 0.69705623 ... 0.69705623 0.69705623 0.69705623]
  [0.40618116 0.38058525 0.35613668 ... 0.50632167 0.46980849 0.43847826]
  [0.3698447  0.34001487 0.31375253 ... 0.5667814  0.47558281 0.41634357]
  ...
  [3.0256865  3.10843945 3.09769988 ... 2.68319392 2.83009195 2.94401383]
  [1.53690648 1.55143607 1.53865254 ... 1.48764002 1.51016057 1.53084517]
  [1.07453525 1.07453525 1.07453525 ... 1.07453525 1.07453525 1.07453525]]

 [[0.40244162 0.40244162 0.40244162 ... 0.40244162 0.40244162 0.40244162]
  [0.25954834 0.24445222 0.23163916 ... 0.31624058 0.29465857 0.27648363]
  [0.32324952 0.28328514 0.24860637 ... 0.51527196 0.44495085 0.37577921]
  ...
  [3.05381346 3.1707437  3.2424273

(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[227.23696899 227.23838806 227.23707581 ... 227.23712158 227.2371521
   227.23953247]
  [223.94630432 223.05818176 222.21153259 ... 226.95544434 226.01856995
   225.04350281]
  [224.17070007 222.06486511 220.56982422 ... 230.0289917  227.78657532
   225.85552979]
  ...
  [238.07844543 239.53102112 240.89369202 ... 234.56340027 235.31465149
   236.48599243]
  [228.28840637 228.39237976 228.53547668 ... 227.8626709  227.77597046
   227.95664978]
  [220.20483398 220.20133972 220.17739868 ... 220.10806274 220.07487488
   220.1640625 ]]

 [[220.71112061 220.71281433 220.71124268 ... 220.71131897 220.71130371
   220.713974  ]
  [219.22244263 217.94403076 217.35571289 ... 222.77511597 221.53181458
   220.79405212]
  [220.78042603 217.98155212 215.29927063 ... 228.60992432 225.63278198
   223.00262451]
  ...
  [247.52252197 249.02714539 250.62088013 ... 245.85716248 246.31027222
   246.90556335]
  [242

(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[235.15731812 235.15696716 235.15742493 ... 235.15696716 235.15670776
   235.15592957]
  [247.67979431 246.5229187  245.60418701 ... 250.21025085 249.5168457
   248.43463135]
  [248.1643219  246.41548157 242.52552795 ... 254.33924866 252.65336609
   250.2053833 ]
  ...
  [264.8586731  264.87231445 265.32989502 ... 259.76818848 263.27301025
   263.00942993]
  [245.9443512  247.09667969 246.7870636  ... 242.85549927 245.32037354
   244.72773743]
  [228.70028687 228.71620178 228.67411804 ... 228.5491333  228.50788879
   229.08198547]]

 [[223.08283997 223.08325195 223.08296204 ... 223.08251953 223.08226013
   223.08256531]
  [238.19700623 237.95422363 238.11705017 ... 241.0655365  239.75268555
   238.62982178]
  [239.82409668 237.46707153 233.96629333 ... 246.14959717 243.30960083
   242.94166565]
  ...
  [263.75643921 264.02539062 264.24447632 .

(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [-4.00609636e+00 -3.87033200e+00 -3.68904781e+00 ... -4.16452312e+00
    -4.24128866e+00 -4.16698647e+00]
   [ 4.96999168e+00  5.06152105e+00  5.16364956e+00 ...  4.85581493e+00
     4.92874765e+00  4.98541260e+00]
   ...
   [-1.78938878e+00 -2.03385878e+00 -2.47877669e+00 ... -1.96386194e+00
    -1.89017963e+00 -1.75011456e+00]
   [-9.75219822e+00 -9.93485069e+00 -9.94738865e+00 ... -8.87953663e+00
    -9.04526997e+00 -9.26321507e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]]

  [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [-2.68009806e+00 -2.46328664e+00 -2.21123648e+00 ... -2.75602961e+00
    -2.72324109e+00 -2.72449350e+00]
   [ 3.39320421e+00  3.38634825e+00  3.47893476e+00 ...  3.74127793e+00
     3.694377

(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.91997409  0.3174122  -0.24848841 ...  2.57996011  1.9901005
    1.43729997]
  [ 4.10245419  3.72696662  3.3481369  ...  5.79234886  5.18506432
    4.57628489]
  ...
  [19.35141563 19.31924248 19.35749626 ... 18.84341812 19.30647087
   19.53071785]
  [15.88591766 16.00092697 15.8267231  ... 15.53110504 15.71146297
   15.72087574]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]]

 [[ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 6.89218473  6.50314379  6.16144991 ...  8.04875851  7.67647839
    7.32396889]
  [ 9.75637436  9.20226669  8.67917919 ... 10.34420586 10.21170807
   10.11451912]
  ...
  [ 4.71768045  4.77019882  4.87262487 ...  4.30613184  4.43348265
    4.59638023]
  [ 1.58035314  1.78931057  2.09620762

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [1.05179749e+02 1.05263596e+02 1.03211029e+02 ... 9.90672836e+01
    1.04126526e+02 1.05516411e+02]
   [1.07692696e+02 1.08135925e+02 1.09457214e+02 ... 9.98967361e+01
    1.01622063e+02 1.05068184e+02]
   ...
   [2.44799011e+02 2.50673309e+02 2.66975220e+02 ... 2.33814804e+02
    2.25030930e+02 2.30541595e+02]
   [4.21385223e+02 4.30500305e+02 4.10286377e+02 ... 3.68078156e+02
    3.81375336e+02 3.90996643e+02]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]]

  [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [6.89181671e+01 7.10281525e+01 7.32584381e+01 ... 6.54438248e+01
    6.82282333e+01 7.05395508e+01]
   [6.05574989

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [-1.30119276e+00 -1.59770727e+00 -3.93001747e+00 ...  2.68644243e-01
     4.17279720e-01 -2.48837137e+00]
   [-2.85983324e+00 -1.78416777e+00 -5.13763762e+00 ...  1.39692712e+00
    -6.82861686e-01 -3.42142135e-01]
   ...
   [-7.70793736e-01 -5.60961294e+00 -1.46768057e+00 ... -4.36538315e+00
     1.13427937e+00 -6.61695099e+00]
   [ 1.62873745e-01 -2.75806808e+00 -4.04852152e-01 ... -3.05547619e+00
    -7.60719955e-01 -3.83139110e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]]

  [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [-6.48540318e-01 -7.41676390e-01 -1.67331088e+00 ... -7.03524828e-01
     6.13375664e-01 -1.04681230e+00]
   [-1.58676338e+

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [-3.78313189e-06 -4.61876562e-06 -1.00797670e-05 ... -7.19351192e-08
    -1.48003323e-07 -6.17690557e-06]
   [-6.01807915e-06 -3.91990716e-06 -1.05628696e-05 ...  2.54395627e-06
    -1.64371806e-06 -9.81043172e-07]
   ...
   [-6.98093231e-07 -9.76893079e-06 -2.10834878e-06 ... -7.11799476e-06
     2.84127032e-06 -1.15097810e-05]
   [ 2.91873289e-06 -2.95558607e-06  5.66381175e-07 ... -3.24186294e-06
     8.09032542e-07 -5.25077712e-06]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
  

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [-2.88229462e+02 -3.38909973e+02 -8.78294617e+02 ...  6.28213310e+01
     1.05308174e+02 -5.39074768e+02]
   [-6.20572266e+02 -3.92831451e+02 -1.14176160e+03 ...  3.20136353e+02
    -1.30603577e+02 -5.77747993e+01]
   ...
   [-1.67565384e+02 -1.18235559e+03 -3.07525238e+02 ... -9.10624084e+02
     2.31266815e+02 -1.37739771e+03]
   [ 4.49125528e+00 -5.92284180e+02 -1.01096008e+02 ... -6.25283142e+02
    -1.78559235e+02 -8.15604126e+02]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]]

  [[ 0.00000000e+00  0.00000000

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 1.59385729e+01  1.11556063e+01  1.64938755e+01 ...  1.35778144e-01
     6.60480022e+00  1.05422649e+01]
   [-2.99645138e+01 -1.14223957e+01 -5.02587624e+01 ...  3.25136995e+00
    -1.52014942e+01 -6.95017910e+00]
   ...
   [ 4.30097084e+01  2.63861427e+01  4.94451141e+01 ...  1.87146664e+01
     4.58137817e+01  3.31604195e+01]
   [ 3.22238045e+01  6.36326485e+01  2.12322083e+01 ...  7.63149872e+01
     3.56814919e+01  7.29867859e+01]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]]

  [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 3.59808612e+00  4.08078671e+00  8.21751475e-01 ...  5.61443269e-01
    -7.22067505e-02 -1.52853981e-01]
   [-1.30437040e+01 -4.30724049e+0

(1, 26, 60, 128)
[[[[  0.           0.           0.         ...   0.
      0.           0.        ]
   [202.27250671 203.34851074 203.63415527 ... 140.89332581
    207.92572021 142.98944092]
   [140.03933716 152.84526062 173.01377869 ... 113.42959595
    117.57209015 124.7495575 ]
   ...
   [403.2565918  413.72616577 397.64852905 ... 316.33151245
    371.04852295 342.68157959]
   [781.85577393 664.65924072 580.18121338 ... 552.31555176
    676.45739746 641.04266357]
   [  0.           0.           0.         ...   0.
      0.           0.        ]]

  [[  0.           0.           0.         ...   0.
      0.           0.        ]
   [ 70.71659851 100.73095703 119.04335785 ...  86.32352448
     85.09532928  94.04341125]
   [ 52.22829056  58.17870331  82.62340546 ...  49.37802124
     67.76906586  46.17280197]
   ...
   [124.770401   185.20153809 184.80226135 ... 159.25314331
    152.21635437 140.59187317]
   [234.72853088 241.10853577 252.45283508 ... 235.79974365
    249.58247375 236.

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [-4.71315969e+05 -5.72462500e+05 -1.43565825e+06 ...  1.00495570e+05
     1.61868344e+05 -8.96436375e+05]
   [-1.03001794e+06 -6.46299562e+05 -1.87411350e+06 ...  5.13758000e+05
    -2.32897328e+05 -1.12179211e+05]
   ...
   [-2.75380594e+05 -1.93272262e+06 -5.13934875e+05 ... -1.50180612e+06
     3.72802094e+05 -2.27622575e+06]
   [ 4.43527852e+04 -9.56987500e+05 -1.48899984e+05 ... -1.04963512e+06
    -2.70107375e+05 -1.32554062e+06]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [6.67071838e+01 7.61022873e+01 5.72524529e+01 ... 5.44500389e+01
    5.90956764e+01 4.89672050e+01]
   [4.48443680e+01 3.89829178e+01 5.23987236e+01 ... 3.74026871e+01
    3.97200584e+01 4.88636322e+01]
   ...
   [9.78996582e+01 7.28534088e+01 7.39156799e+01 ... 6.85039825e+01
    8.49497070e+01 7.64152451e+01]
   [1.11938194e+02 9.90079956e+01 8.80274124e+01 ... 1.13616646e+02
    9.53267899e+01 9.78992920e+01]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]]

  [[0.00000000e+00 0.00000000e+00

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[0.1        0.1        0.1        ... 0.1        0.1
    0.1       ]
   [0.1        0.1        0.1        ... 0.1        0.1
    0.1       ]
   [0.1        0.1        0.1        ... 0.1        0.1
    0.1       ]
   ...
   [0.1        0.1        0.1        ... 0.1        0.1
    0.1       ]
   [0.1        0.1        0.1        ... 0.1        0.1
    0.1       ]
   [0.1        0.1        0.1        ... 0.1        0.1
    0.1       ]]

  [[0.1        0.1        0.1        ... 0.1        0.1
    0.1       ]
   [0.1        0.1        0.1        ... 0.1        0.1
    0.1       ]
   [0.1        0.1        0.1        ... 0.1        0.1
    0.1       ]
   ...
   [0.1        0.1        0.1        ... 0.1        0.1
    0.1       ]
   [0.1        0.1        0.1        ... 0.1        0.1
    0.1       ]
   [0.1        0.1        0.1        ... 0.1        0.1
    0.1       ]]

  [[0.1        0.1        0.1        ... 0.1        0.1
    0.1    

(22, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[37323.75390625 37323.75390625 37323.75390625 ... 37323.75390625
    37323.75390625 37323.75390625]
   [37346.38671875 37366.27734375 37385.5        ... 37280.07421875
    37302.68359375 37324.89453125]
   [37408.88671875 37440.92578125 37468.98828125 ... 37287.47265625
    37332.0078125  37372.453125  ]
   ...
   [34948.5390625  34941.27734375 34935.46875    ... 34994.9921875
    34976.015625   34960.64453125]
   [34966.29296875 34961.35546875 34959.75390625 ... 34987.7734375
    34980.0078125  34973.6796875 ]
   [34997.28125    34997.28125    34997.28125    ... 34997.28125
    34997.28125    3499

(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
(1, 60, 128)
[[[5000.12304688 5000.12304688 5000.12304688 ... 5000.12304688
   5000.12304688 5000.12304688]
  [5004.15283203 5002.74560547 5001.34960938 ... 5004.73291016
   5004.93603516 5004.96435547]
  [5015.69628906 5009.24023438 5003.359375   ... 5027.09082031
   5024.95117188 5021.19189453]
  ...
  [5128.31884766 5129.76757812 5130.27148438 ... 5116.23046875
   5121.61425781 5125.76318359]
  [5057.22216797 5057.61328125 5057.99755859 ... 5053.31689453
   5054.90722656 5056.39746094]
  [5015.21582031 5015.21582031 5015.21582031 ... 5015.21582031
   5015.21582031 5015.21582031]]

 [[4860.36523438 4860.36523438 4860.36523438 ... 4860.36523438
   4860.36523438 4860.36523438]
  [4876.75195312 4875.35888672 4873.48730469 ... 4875.38525391
   4877.08789062 4877.38769531]
  [4915.26464844 4908.11767578 4900.40039062 ... 4921.12646484


(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   ...
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]]

  [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.000000

(22, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[1.39344128e+09 1.39344128e+09 1.39344128e+09 ... 1.39344128e+09
    1.39344128e+09 1.39344128e+09]
   [1.39511629e+09 1.39660147e+09 1.39803763e+09 ... 1.39016870e+09
    1.39185549e+09 1.39351245e+09]
   [1.39974899e+09 1.40214618e+09 1.40424742e+09 ... 1.39068365e+09
    1.39400640e+09 1.39702656e+09]
   ...
   [1.22147891e+09 1.22096947e+09 1.22056115e+09 ... 1.22473165e+09
    1.22340211e+09 1.22232563e+09]
   [1.22274304e+09 1.22239616e+09 1.22228429e+09 ... 1.22424896e+09
    1.22370560e+09 1.22326221e+09]
   [1.22493082e+09 1.22493082e+09 1.22493082e+09 ... 1.22493082e+09
    1.22493082e+09

(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
(1, 26, 60, 128)
[[[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   ...
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    0.00000000e+00 0.00000000e+00]]


[[[[5.02968722e-10 5.02968722e-10 5.02968722e-10 ... 5.02968722e-10
    5.02968722e-10 5.02968722e-10]
   [4.97712260e-10 4.95359809e-10 4.93192653e-10 ... 5.05845144e-10
    5.02937969e-10 5.00235020e-10]
   [4.90744889e-10 4.87065388e-10 4.84073615e-10 ... 5.05587794e-10
    4.99992825e-10 4.95029739e-10]
   ...
   [5.99654881e-10 6.00328287e-10 6.00600292e-10 ... 5.93545657e-10
    5.96395766e-10 5.98402994e-10]
   [6.01571182e-10 6.02046302e-10 6.02425887e-10 ... 5.99182370e-10
    6.00140548e-10 6.00928252e-10]
   [6.03551042e-10 6.03548378e-10 6.03532835e-10 ... 6.03532835e-10
    6.03548378e-10 6.03535499e-10]]

  [[5.12965226e-10 5.12965226e-10 5.12965226e-10 ... 5.12965226e-10
    5.12965226e-10 5.12965226e-10]
   [4.91494290e-10 4.86749752e-10 4.82396234e-10 ... 5.08160236e-10
    5.02196618e-10 4.96632735e-10]
   [4.75989470e-10 4.68927230e-10 4.63352995e-10 ... 5.06236886e-10
    4.94787600e-10 4.84635720e-10]
   ...
   [6.96045277e-10 6.97886748e-10 6.98892666e-10 ... 6.80