<center> <font color = #82318E size = 5 face = "微软雅黑" > NetCDF4 Test </font> </center>

In [1]:
import os
import numpy as np
import pandas as pd
import netCDF4 as nc

import keras 
import tensorflow as tf

import seaborn as sns
import matplotlib.pyplot as plt

Using TensorFlow backend.


<center> <font color = #82318E size = 4 face = "微软雅黑" > 1. Sample Data </font> </center>

<center> <font color = #82318E size = 3 face = "微软雅黑" > 1.1 CPL </font> </center>

<center> <font color = #82318E size = 3 face = "微软雅黑" > 1.1.1 Read </font> </center>

In [3]:
dir = './Samples/cpl/'
nc_temp_list = list()

for file in os.listdir(dir):
    if file.split('.')[-1] == 'nc':
        print(file)
        nc_temp_list.append('{}{}'.format(dir, file))
print()

for i in np.arange(len(nc_temp_list)):
    print(nc_temp_list[i])

S_LGM-21ka.cpl6.ha.0550-01.nc

./Samples/cpl/S_LGM-21ka.cpl6.ha.0550-01.nc


<center> <font color = #82318E size = 3 face = "微软雅黑" > 1.1.2 Variables </font> </center>

In [4]:
temp_pointer = nc.Dataset(nc_temp_list[0])

temp_dict = {}

for j in np.arange(len(list(temp_pointer.variables.keys()))):
    temp = temp_pointer.variables[list(temp_pointer.variables.keys())[j]]
    '''    
    print('-'*25 + ' Variable {0:03d} '.format(j) + '-'*25)
    print(temp.name)
    print(temp.long_name)
    print(temp.shape)
    print('-'*64, end = '\n'*2)
    '''
    temp_dict.setdefault('{0:03d}'.format(j), [temp.name, temp.long_name, temp.shape])
    
temp_df = pd.DataFrame(temp_dict, index = ['Name', 'Long_name', 'Shape']).transpose()
print(temp_df)

temp_df.to_excel('{}cpl_Variables.xlsx'.format(dir), sheet_name = 'Sheet1')

                     Name                         Long_name          Shape
000                  time                              time           (1,)
001            time_bound  time average interval boundaries         (1, 2)
002          domain_a_lat                          latitude      (60, 128)
003          domain_a_lon                         longitude      (60, 128)
004         domain_a_area                         cell area      (60, 128)
005        domain_a_aream           cell area from map file      (60, 128)
006        domain_a_index                      global index      (60, 128)
007         domain_a_mask                       domain mask      (60, 128)
008          domain_a_pid                        process ID      (60, 128)
009         avXa2c_a_Sa_z                            height   (1, 60, 128)
010         avXa2c_a_Sa_u                   velocity, zonal   (1, 60, 128)
011         avXa2c_a_Sa_v              velocity, meridional   (1, 60, 128)
012      avXa2c_a_Sa_tbot

<center> <font color = #82318E size = 3 face = "微软雅黑" > 1.2 ICE </font> </center>

<center> <font color = #82318E size = 3 face = "微软雅黑" > 1.2.1 Read </font> </center>

In [4]:
dir = './Samples/ice/'
nc_temp_list = list()

for file in os.listdir(dir):
    if file.split('.')[-1] == 'nc':
        print(file)
        nc_temp_list.append('{}{}'.format(dir, file))
print()

for i in np.arange(len(nc_temp_list)):
    print(nc_temp_list[i])

S_LGM-21ka.cice.h.0550-01.nc

./Samples/ice/S_LGM-21ka.cice.h.0550-01.nc


<center> <font color = #82318E size = 3 face = "微软雅黑" > 1.2.2 Variables </font> </center>

In [5]:
temp_pointer = nc.Dataset(nc_temp_list[0])

temp_dict = {}

for j in np.arange(len(list(temp_pointer.variables.keys()))):
    temp = temp_pointer.variables[list(temp_pointer.variables.keys())[j]]
    '''    
    print('-'*25 + ' Variable {0:03d} '.format(j) + '-'*25)
    print(temp.name)
    print(temp.long_name)
    print(temp.shape)
    print('-'*64, end = '\n'*2)
    '''
    temp_dict.setdefault('{0:03d}'.format(j), [temp.name, temp.long_name, temp.shape])
    
temp_df = pd.DataFrame(temp_dict, index = ['Name', 'Long_name', 'Shape']).transpose()
print(temp_df)

temp_df.to_excel('{}ice_Variables.xlsx'.format(dir), sheet_name = 'Sheet2')

            Name                                          Long_name  \
000         time                                         model time   
001  time_bounds             boundaries for time-averaging interval   
002         TLON                            T grid center longitude   
003         TLAT                             T grid center latitude   
004         ULON                            U grid center longitude   
005         ULAT                             U grid center latitude   
006        tmask                                    ocean grid mask   
007        tarea                               area of T grid cells   
008        uarea                               area of U grid cells   
009        ANGLE      angle grid makes with latitude line on U grid   
010       ANGLET      angle grid makes with latitude line on T grid   
011           hi                       grid cell mean ice thickness   
012           hs                      grid cell mean snow thickness   
013   

<center> <font color = #82318E size = 3 face = "微软雅黑" > 1.3 LND </font> </center>

<center> <font color = #82318E size = 3 face = "微软雅黑" > 1.3.1 Read </font> </center>

In [6]:
dir = './Samples/lnd/'
nc_temp_list = list()

for file in os.listdir(dir):
    if file.split('.')[-1] == 'nc':
        print(file)
        nc_temp_list.append('{}{}'.format(dir, file))
print()

for i in np.arange(len(nc_temp_list)):
    print(nc_temp_list[i])

S_LGM-21ka.clm2.h0.0550-01.nc

./Samples/lnd/S_LGM-21ka.clm2.h0.0550-01.nc


<center> <font color = #82318E size = 3 face = "微软雅黑" > 1.3.2 Variables </font> </center>

In [8]:
temp_pointer = nc.Dataset(nc_temp_list[0])

temp_dict = {}

for j in np.arange(len(list(temp_pointer.variables.keys()))):
    temp = temp_pointer.variables[list(temp_pointer.variables.keys())[j]]
         
    print('-'*25 + ' Variable {0:03d} '.format(j) + '-'*25)
    print(temp.name)
      
    if temp.name != 'time' and temp.name != 'mcdate' and temp.name != 'mcsec' and temp.name != 'mdcur' and \
    temp.name != 'mscur' and temp.name != 'nstep' and temp.name != 'time_bounds' and temp.name != 'date_written' and temp.name != 'time_written':
        print(temp.long_name)
    elif temp.name != 'date_written' and temp.name != 'time_written':
        print(temp.logname)
    else:
        print(temp.name)
        
    print(temp.shape)
    print('-'*64, end = '\n'*2)
    
    if temp.name == 'time' or temp.name == 'mcdate' or temp.name == 'mcsec' or temp.name == 'mdcur' or \
    temp.name == 'mscur' or temp.name == 'nstep' or temp.name == 'time_bounds':
        temp_dict.setdefault('{0:03d}'.format(j), [temp.name, temp.logname, temp.shape])        
    elif temp.name == 'date_written' or temp.name == 'time_written':
        temp_dict.setdefault('{0:03d}'.format(j), [temp.name, temp.name, temp.shape])
    else:
        temp_dict.setdefault('{0:03d}'.format(j), [temp.name, temp.long_name, temp.shape])
    
temp_df = pd.DataFrame(temp_dict, index = ['Name', 'Long_name', 'Shape']).transpose()
print(temp_df)

temp_df.to_excel('{}lnd_Variables.xlsx'.format(dir), sheet_name = 'Sheet3')

------------------------- Variable 000 -------------------------
lon
coordinate longitude
(128,)
----------------------------------------------------------------

------------------------- Variable 001 -------------------------
lat
coordinate latitude
(60,)
----------------------------------------------------------------

------------------------- Variable 002 -------------------------
lonrof
runoff coordinate longitude
(720,)
----------------------------------------------------------------

------------------------- Variable 003 -------------------------
latrof
runoff coordinate latitude
(360,)
----------------------------------------------------------------

------------------------- Variable 004 -------------------------
time
time
(1,)
----------------------------------------------------------------

------------------------- Variable 005 -------------------------
levsoi
coordinate soil levels
(10,)
----------------------------------------------------------------

------------------

<center> <font color = #82318E size = 3 face = "微软雅黑" > 1.4 OCN </font> </center>

<center> <font color = #82318E size = 3 face = "微软雅黑" > 1.4.1 Read </font> </center>

In [9]:
dir = './Samples/ocn/'
nc_temp_list = list()

for file in os.listdir(dir):
    if file.split('.')[-1] == 'nc':
        print(file)
        nc_temp_list.append('{}{}'.format(dir, file))
print()

for i in np.arange(len(nc_temp_list)):
    print(nc_temp_list[i])

MMEAN0550-01.nc

./Samples/ocn/MMEAN0550-01.nc


<center> <font color = #82318E size = 3 face = "微软雅黑" > 1.4.2 Variables </font> </center>

In [10]:
temp_pointer = nc.Dataset(nc_temp_list[0])

temp_dict = {}

for j in np.arange(len(list(temp_pointer.variables.keys()))):
    temp = temp_pointer.variables[list(temp_pointer.variables.keys())[j]]
    '''    
    print('-'*25 + ' Variable {0:03d} '.format(j) + '-'*25)
    print(temp.name)
    print(temp.long_name)
    print(temp.shape)
    print('-'*64, end = '\n'*2)
    '''
    temp_dict.setdefault('{0:03d}'.format(j), [temp.name, temp.long_name, temp.shape])
    
temp_df = pd.DataFrame(temp_dict, index = ['Name', 'Long_name', 'Shape']).transpose()
print(temp_df)

temp_df.to_excel('{}ocn_Variables.xlsx'.format(dir), sheet_name = 'Sheet4')

            Name                                          Long_name  \
000          lat                              latitude (on T grids)   
001          lon                             longitude (on T grids)   
002          lev                                 depth (on T grids)   
003         lev1                                 depth (on V grids)   
004    num_basin  Basin index(1 Global,2 Arctic+Atlantic,3 India...   
005         time                                               time   
006           z0                                 sea surface height   
007           hi                                   thickness of ice   
008           hd                       thickness of ice in one grid   
009          ic1  total of number of levels involved in convecti...   
010          ic2                number of levels ventilated per day   
011         net1                              net surface heat flux   
012         net2                              net surface salt flux   
013   

<center> <font color = #82318E size = 4 face = "微软雅黑" > 2. TimeSeries Data </font> </center>

In [26]:
dir = './Tensor/TimeSeries/'
temp_list = list()

for file in os.listdir(dir):
    if file.split('.')[-1] == 'nc':
        '''
        print(file)
        '''
        temp_list.append('{}{}'.format(dir, file))

for i in np.arange(len(temp_list)):
    '''
    print(temp_list[i])
    '''

print(len(temp_list))

120


In [32]:
for i in temp_list:
    
    temp_pointer = nc.Dataset(i)
    time = temp_pointer.variables['time']
    
    '''
    print('='*64 + '\n' + '{}'.format(i))
    print(time.units)
    '''
    
    print(nc.num2date(time[:], time.units, calendar = '365_day'), end = '\n'*2)

[cftime.DatetimeNoLeap(550, 1, 16, 11, 31, 12, 0, 5, 16)]

[cftime.DatetimeNoLeap(550, 2, 14, 23, 31, 12, 0, 6, 45)]

[cftime.DatetimeNoLeap(550, 3, 16, 11, 31, 12, 0, 1, 75)]

[cftime.DatetimeNoLeap(550, 4, 15, 23, 31, 12, 0, 3, 105)]

[cftime.DatetimeNoLeap(550, 5, 16, 11, 31, 12, 0, 6, 136)]

[cftime.DatetimeNoLeap(550, 6, 15, 23, 31, 12, 0, 1, 166)]

[cftime.DatetimeNoLeap(550, 7, 16, 11, 31, 12, 0, 4, 197)]

[cftime.DatetimeNoLeap(550, 8, 16, 11, 31, 12, 0, 0, 228)]

[cftime.DatetimeNoLeap(550, 9, 15, 23, 31, 12, 0, 2, 258)]

[cftime.DatetimeNoLeap(550, 10, 16, 11, 31, 12, 0, 5, 289)]

[cftime.DatetimeNoLeap(550, 11, 15, 23, 31, 12, 0, 0, 319)]

[cftime.DatetimeNoLeap(550, 12, 16, 11, 31, 12, 0, 3, 350)]

[cftime.DatetimeNoLeap(551, 1, 16, 11, 31, 12, 0, 6, 16)]

[cftime.DatetimeNoLeap(551, 2, 14, 23, 31, 12, 0, 0, 45)]

[cftime.DatetimeNoLeap(551, 3, 16, 11, 31, 12, 0, 2, 75)]

[cftime.DatetimeNoLeap(551, 4, 15, 23, 31, 12, 0, 4, 105)]

[cftime.DatetimeNoLeap(551, 5, 16, 11, 31, 

In [57]:
string = 'avXc2o_o_Foxx_salt'

J = nc.Dataset(temp_list[0]).variables[string].shape[-2]
K = nc.Dataset(temp_list[0]).variables[string].shape[-1]
I = len(temp_list)

temp_matrix = np.ones((I, J, K))
print(temp_matrix.shape)

for i in np.arange(len(temp_list)):
    
    temp_pointer = nc.Dataset(temp_list[i])
    salt_flux = temp_pointer.variables[string]
    print(salt_flux.shape)
    temp_matrix[i, ::, ::] = salt_flux[0, ::, ::]

np.save('./Tensor/{}.npy'.format(string), temp_matrix)

(120, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 196, 360)
(1, 

In [56]:
load_matrix = np.load('./Tensor/{}.npy'.format(string))
print(load_matrix.shape)

(120, 196, 360)


<center> <font color = #82318E size = 4 face = "微软雅黑" > -1. Test </font> </center>

<center> <font color = #82318E size = 3 face = "微软雅黑" > -1.1 Read </font> </center>

In [11]:
dir = './Test/'
nc_temp_list = list()

for file in os.listdir(dir):
    if file.split('.')[-1] == 'nc':
        print(file)
        nc_temp_list.append('{}{}'.format(dir, file))
print()

for i in np.arange(len(nc_temp_list)):
    print(nc_temp_list[i])

S_LGM-21ka.cpl6.ha.0550-01.nc
S_LGM-21ka.cpl6.ha.0550-02.nc
S_LGM-21ka.cpl6.ha.0649-12.nc

./Test/S_LGM-21ka.cpl6.ha.0550-01.nc
./Test/S_LGM-21ka.cpl6.ha.0550-02.nc
./Test/S_LGM-21ka.cpl6.ha.0649-12.nc


<center> <font color = #82318E size = 3 face = "微软雅黑" > -1.2 Fundamental Operation </font> </center>

In [12]:
for i in nc_temp_list:
    
    temp_pointer = nc.Dataset(i)
    print('='*64 + '\n' + '{}'.format(i) + '\n' + '='*64, end = '\n'*2)
    

    print(temp_pointer.variables.keys())

    for j in np.arange(len(list(temp_pointer.variables.keys()))):
        temp = temp_pointer.variables[list(temp_pointer.variables.keys())[j]]
        print('-'*25 + ' Variable {0:03d} '.format(j) + '-'*25)
        print(temp)
        print(temp.shape)
        print(temp[::])
        print('-'*64, end = '\n'*2)

./Test/S_LGM-21ka.cpl6.ha.0550-01.nc

odict_keys(['time', 'time_bound', 'domain_a_lat', 'domain_a_lon', 'domain_a_area', 'domain_a_aream', 'domain_a_index', 'domain_a_mask', 'domain_a_pid', 'avXa2c_a_Sa_z', 'avXa2c_a_Sa_u', 'avXa2c_a_Sa_v', 'avXa2c_a_Sa_tbot', 'avXa2c_a_Sa_ptem', 'avXa2c_a_Sa_shum', 'avXa2c_a_Sa_dens', 'avXa2c_a_Sa_pbot', 'avXa2c_a_Sa_pslv', 'avXa2c_a_Faxa_lwdn', 'avXa2c_a_Faxa_rainc', 'avXa2c_a_Faxa_rainl', 'avXa2c_a_Faxa_snowc', 'avXa2c_a_Faxa_snowl', 'avXa2c_a_Faxa_swndr', 'avXa2c_a_Faxa_swvdr', 'avXa2c_a_Faxa_swndf', 'avXa2c_a_Faxa_swvdf', 'avXa2c_a_Faxa_swnet', 'domain_i_lat', 'domain_i_lon', 'domain_i_area', 'domain_i_aream', 'domain_i_index', 'domain_i_mask', 'domain_i_pid', 'avXi2c_i_Si_t', 'avXi2c_i_Si_tref', 'avXi2c_i_Si_qref', 'avXi2c_i_Si_ifrac', 'avXi2c_i_Si_avsdr', 'avXi2c_i_Si_anidr', 'avXi2c_i_Si_avsdf', 'avXi2c_i_Si_anidf', 'avXi2c_i_index', 'avXi2c_i_Faii_taux', 'avXi2c_i_Faii_tauy', 'avXi2c_i_Faii_lat', 'avXi2c_i_Faii_sen', 'avXi2c_i_Faii_lwup', 'avX

[[[-- -- -- ... -- -- --]
  [-- -- -- ... -- -- --]
  [-- -- -- ... -- -- --]
  ...
  [-- -- -- ... -- -- --]
  [-- -- -- ... -- -- --]
  [-- -- -- ... -- -- --]]]
----------------------------------------------------------------

------------------------- Variable 050 -------------------------
<class 'netCDF4._netCDF4.Variable'>
float32 avXi2c_i_Faii_swnet(time, nj_i, ni_i)
    long_name: rad, sw, net
    units: W/m^2
    missing_value: 1e+30
    _FillValue: 1e+30
    cell_method: time: mean
unlimited dimensions: time
current shape = (1, 196, 360)
filling on
(1, 196, 360)
[[[-- -- -- ... -- -- --]
  [-- -- -- ... -- -- --]
  [-- -- -- ... -- -- --]
  ...
  [-- -- -- ... -- -- --]
  [-- -- -- ... -- -- --]
  [-- -- -- ... -- -- --]]]
----------------------------------------------------------------

------------------------- Variable 051 -------------------------
<class 'netCDF4._netCDF4.Variable'>
float32 avXi2c_i_Fioi_swpen(time, nj_i, ni_i)
    long_name: rad, sw, penetrating
    unit

------------------------- Variable 100 -------------------------
<class 'netCDF4._netCDF4.Variable'>
float32 avXr2c_r_Forr_roff(time, nj_r, ni_r)
    long_name: water flux: runoff
    units: kg/s/m^2
    missing_value: 1e+30
    _FillValue: 1e+30
    cell_method: time: mean
unlimited dimensions: time
current shape = (1, 360, 720)
filling on
(1, 360, 720)
[[[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
   0.0000000e+00 0.0000000e+00]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
   0.0000000e+00 0.0000000e+00]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
   0.0000000e+00 0.0000000e+00]
  ...
  [7.4629534e-20 7.4629534e-20 6.0589842e-20 ... 5.5349576e-20
   7.4629534e-20 7.4629534e-20]
  [7.4629534e-20 7.4629534e-20 6.0589842e-20 ... 5.5349576e-20
   7.4629534e-20 7.4629534e-20]
  [7.4629534e-20 7.4629534e-20 6.0589842e-20 ... 5.5349576e-20
   7.4629534e-20 7.4629534e-20]]]
----------------------------------------------------------------


[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
----------------------------------------------------------------

------------------------- Variable 158 -------------------------
<class 'netCDF4._netCDF4.Variable'>
float32 avXc2o_o_Sa_pslv(time, nj_o, ni_o)
    long_name: pressure, sea level
    units: Pa
    missing_value: 1e+30
    _FillValue: 1e+30
    cell_method: time: mean
unlimited dimensions: time
current shape = (1, 196, 360)
filling on
(1, 196, 360)
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
----------------------------------------------------------------

------------------------- Variable 159 -------------------------
<class 'netCDF4._netCDF4.Variable'>
float32 avXc2o_o_Faoc_duu10n(time, nj_o, ni_o)
    long_name: 10m neutral wind speed squa

<class 'netCDF4._netCDF4.Variable'>
float32 domain_i_index(nj_i, ni_i)
    long_name: global index
unlimited dimensions: 
current shape = (196, 360)
filling on, default _FillValue of 9.969209968386869e+36 used

(196, 360)
[[1.0000e+00 2.0000e+00 3.0000e+00 ... 3.5800e+02 3.5900e+02 3.6000e+02]
 [3.6100e+02 3.6200e+02 3.6300e+02 ... 7.1800e+02 7.1900e+02 7.2000e+02]
 [7.2100e+02 7.2200e+02 7.2300e+02 ... 1.0780e+03 1.0790e+03 1.0800e+03]
 ...
 [6.9481e+04 6.9482e+04 6.9483e+04 ... 6.9838e+04 6.9839e+04 6.9840e+04]
 [6.9841e+04 6.9842e+04 6.9843e+04 ... 7.0198e+04 7.0199e+04 7.0200e+04]
 [7.0201e+04 7.0202e+04 7.0203e+04 ... 7.0558e+04 7.0559e+04 7.0560e+04]]
----------------------------------------------------------------

------------------------- Variable 033 -------------------------
<class 'netCDF4._netCDF4.Variable'>
float32 domain_i_mask(nj_i, ni_i)
    long_name: domain mask
unlimited dimensions: 
current shape = (196, 360)
filling on, default _FillValue of 9.969209968386869e+36 

<class 'netCDF4._netCDF4.Variable'>
float32 avXo2c_o_So_dhdx(time, nj_o, ni_o)
    long_name: surface slope, zonal
    units: m/m
    missing_value: 1e+30
    _FillValue: 1e+30
    cell_method: time: mean
unlimited dimensions: time
current shape = (1, 196, 360)
filling on
(1, 196, 360)
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
----------------------------------------------------------------

------------------------- Variable 091 -------------------------
<class 'netCDF4._netCDF4.Variable'>
float32 avXo2c_o_So_dhdy(time, nj_o, ni_o)
    long_name: surface slope, meridional
    units: m/m
    missing_value: 1e+30
    _FillValue: 1e+30
    cell_method: time: mean
unlimited dimensions: time
current shape = (1, 196, 360)
filling on
(1, 196, 360)
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 

<class 'netCDF4._netCDF4.Variable'>
float32 avXc2l_l_Sa_v(time, nj_l, ni_l)
    long_name: velocity, meridional
    units: m/s^2
    missing_value: 1e+30
    _FillValue: 1e+30
    cell_method: time: mean
unlimited dimensions: time
current shape = (1, 60, 128)
filling on
(1, 60, 128)
[[[ 0.         0.         0.        ...  0.         0.         0.       ]
  [-2.9115515 -2.8921497 -2.269831  ... -2.8234792 -2.813013  -3.176838 ]
  [-3.3745272 -3.5199654 -3.6545715 ... -1.896024  -2.723985  -2.923629 ]
  ...
  [-4.7617297 -4.2503343 -4.143265  ... -6.957681  -6.4403386 -5.427367 ]
  [-2.310453  -2.1202476 -1.6719902 ... -3.030279  -2.7184706 -2.5740898]
  [ 0.         0.         0.        ...  0.         0.         0.       ]]]
----------------------------------------------------------------

------------------------- Variable 142 -------------------------
<class 'netCDF4._netCDF4.Variable'>
float32 avXc2l_l_Sa_tbot(time, nj_l, ni_l)
    long_name: temperature, bottom
    units: kelvin
 

filling on
(1, 60, 128)
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
----------------------------------------------------------------

------------------------- Variable 020 -------------------------
<class 'netCDF4._netCDF4.Variable'>
float32 avXa2c_a_Faxa_rainl(time, nj_a, ni_a)
    long_name: precip, liquid, large-scale
    units: kg/s/m^2
    missing_value: 1e+30
    _FillValue: 1e+30
    cell_method: time: mean
unlimited dimensions: time
current shape = (1, 60, 128)
filling on
(1, 60, 128)
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
----------------------------------------------------------------

------------------------- Variable 021 -------------------------
<class 'netCDF4._netCDF4.Variable'>
float32 avXa2c_a_Faxa_snowc(time, nj_a, ni_a)
    

(1, 60, 128)
[[[-0.2647125  -0.2647158  -0.2647255  ... -0.26468    -0.2646666
   -0.2646768 ]
  [-1.2307149  -1.1284237  -1.0618486  ... -1.261832   -1.2654302
   -1.2967246 ]
  [-2.0484269  -1.9204605  -1.6322223  ... -2.4547508  -2.424377
   -2.0170794 ]
  ...
  [ 0.          0.          0.         ...  0.12628455  0.14374118
    0.        ]
  [ 0.          0.          0.         ...  0.14105801  0.
    0.        ]
  [ 0.02202609  0.02123285  0.02127923 ...  0.02119907  0.0212978
    0.02141381]]]
----------------------------------------------------------------

------------------------- Variable 075 -------------------------
<class 'netCDF4._netCDF4.Variable'>
float32 avXl2c_l_Fall_sen(time, nj_l, ni_l)
    long_name: sensible heat flux
    units: W/m^2
    missing_value: 1e+30
    _FillValue: 1e+30
    cell_method: time: mean
unlimited dimensions: time
current shape = (1, 60, 128)
filling on
(1, 60, 128)
[[[-1.0277572  -1.0277915  -1.027864   ... -1.0274999  -1.0273658
   -1.02745

  [0. 0. 0. ... 0. 0. 0.]]]
----------------------------------------------------------------

------------------------- Variable 130 -------------------------
<class 'netCDF4._netCDF4.Variable'>
float32 avXc2i_i_So_dhdy(time, nj_i, ni_i)
    long_name: surface slope, meridional
    units: m/m
    missing_value: 1e+30
    _FillValue: 1e+30
    cell_method: time: mean
unlimited dimensions: time
current shape = (1, 196, 360)
filling on
(1, 196, 360)
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
----------------------------------------------------------------

------------------------- Variable 131 -------------------------
<class 'netCDF4._netCDF4.Variable'>
float32 avXc2i_i_Fioo_q(time, nj_i, ni_i)
    long_name: q<0 = heat of fusion, q>0 = melt
    units: W/m^2
    missing_value: 1e+30
    _FillValue: 1e+30
    cell_method: time: mean
unlimited dimensions: time
current s

<center> <font color = #82318E size = 3 face = "微软雅黑" > -1.3 Variables' longname </font> </center>

In [13]:
temp_pointer = nc.Dataset(nc_temp_list[0])

for j in np.arange(len(list(temp_pointer.variables.keys()))):
    temp = temp_pointer.variables[list(temp_pointer.variables.keys())[j]]
    print('-'*25 + ' Variable {0:03d} '.format(j) + '-'*25)
    print(temp.name)
    print(temp.long_name)
    print(temp.shape)
    print('-'*64, end = '\n'*2)

------------------------- Variable 000 -------------------------
time
time
(1,)
----------------------------------------------------------------

------------------------- Variable 001 -------------------------
time_bound
time average interval boundaries
(1, 2)
----------------------------------------------------------------

------------------------- Variable 002 -------------------------
domain_a_lat
latitude
(60, 128)
----------------------------------------------------------------

------------------------- Variable 003 -------------------------
domain_a_lon
longitude
(60, 128)
----------------------------------------------------------------

------------------------- Variable 004 -------------------------
domain_a_area
cell area
(60, 128)
----------------------------------------------------------------

------------------------- Variable 005 -------------------------
domain_a_aream
cell area from map file
(60, 128)
----------------------------------------------------------------



<center> <font color = #82318E size = 3 face = "微软雅黑" > -1.4 Time </font> </center>

In [14]:
for i in nc_temp_list:
    
    temp_pointer = nc.Dataset(i)
    print('='*64 + '\n' + '{}'.format(i))

    time = temp_pointer.variables['time']
    print(time.units)
    print(nc.num2date(time[:], 'days since 0001-01-01 00:00:00'), end = '\n'*2)

./Test/S_LGM-21ka.cpl6.ha.0550-01.nc
days since 0000-01-01 00:00:00
[cftime.DatetimeGregorian(550, 9, 1, 11, 31, 12, 0, 3, 244)]

./Test/S_LGM-21ka.cpl6.ha.0550-02.nc
days since 0000-01-01 00:00:00
[cftime.DatetimeGregorian(550, 9, 30, 23, 31, 12, 0, 4, 273)]

./Test/S_LGM-21ka.cpl6.ha.0649-12.nc
days since 0000-01-01 00:00:00
[cftime.DatetimeGregorian(650, 7, 7, 11, 31, 12, 0, 2, 188)]

